### ISSUE TITLE
Compilation of laplacian doesn't work with gcc 4.6/boost 1.54

### ISSUE THREAD

**Issue by cdaversin** [feelpp/feelpp#179]
I've juste update feelpp and I'm trying to compile my applications with gcc 4.6. As it didn't work, I've tried with laplacian example, and I obtain the same error (from boost 1.54) : 

/usr/include/boost/variant/variant.hpp:2058:13: error: no matching function for call to ‘boost::variantboost::weak_ptr<void, boost::signals2::detail::foreign_void_weak_ptr>::move_assigner::assign_impl(boost::weak_ptr<void>&, nothrow_copy, nothrow_move_constructor, boost::variantboost::weak_ptr<void, boost::signals2::detail::foreign_void_weak_ptr>::has_fallback_type_)’

However, no problems with clang or gcc 4.7
