### ISSUE TITLE
failed to compile on ubuntu 12.04 gcc 4.6

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#47]
_Original author: christro...@googlemail.com (September 19, 2012 11:26:38)_

<b>What steps will reproduce the problem?</b>
1.update to latest rev
2.make

We end up with the following errors:

/home/trophime/Projects/feel/git/feelpp/feel/feelalg/solverlinearpetsc.cpp: In member function ‘void Feel::SolverLinearPetsc&lt;T&gt;::setPetscPreconditionerType()’:
/home/trophime/Projects/feel/git/feelpp/feel/feelalg/solverlinearpetsc.cpp:767:45: erreur: ‘PCGASM’ was not declared in this scope

This is certainly connected with the petsc version. Ubuntun 12.04 ships only 3.1 version :( 

_Original issue: http://code.google.com/p/feelpp/issues/detail?id=48_
