### ISSUE TITLE
Bug boost-1.57 matrix ublas

### ISSUE THREAD

**Issue by gdolle** [feelpp/feelpp#478]
Hi, 

Feel fail to compile with boost version 1.57 on my machine. Here's an extract of the error I have

```
In file included from /home/gug/devel/feelpp.git/feel/feelalg/preconditioner.cpp:31:
In file included from /home/gug/devel/feelpp.git/feel/feelalg/preconditioner.hpp:35:
In file included from /home/gug/devel/feelpp.git/feel/feelalg/matrixsparse.hpp:56:
/usr/include/boost/numeric/ublas/matrix.hpp:1387:35: error: unknown type name 'matrix'; did you mean
      'Feel::tag::matrix'?
        fixed_matrix &operator = (matrix m) {
                                  ^
/home/gug/devel/feelpp.git/feel/feelcore/parameter.hpp:69:27: note: 'Feel::tag::matrix' declared here
    BOOST_PARAMETER_NAME( matrix )
                          ^
/usr/include/boost/parameter/name.hpp:140:7: note: expanded from macro 'BOOST_PARAMETER_NAME'
    )(name)                                                         \
      ^
/usr/include/boost/parameter/name.hpp:133:37: note: expanded from macro 'BOOST_PARAMETER_SIMPLE_NAME'
    BOOST_PARAMETER_BASIC_NAME(tag, name, BOOST_PP_CAT(_, name))
                                    ^
/usr/include/boost/parameter/name.hpp:94:14: note: expanded from macro 'BOOST_PARAMETER_BASIC_NAME'
      struct tag
```

It sounds like a problem with the namespace, can someone reproduce this problem to confirm it ?
