### ISSUE TITLE
Package not compiling

### ISSUE THREAD

**Issue by acampove** [feelpp/feelpp#679]
Hi,

I am trying to build feel++ in a virtual machine with Scientific Linux 7 and I am getting some compilation problems while doing `make`. In line 380 of  `/home/acampoverde/Programs/feelpp-0.100.0-beta.7/feel/feelalg/preconditioner.hpp` I have:
```sh
Feel::detail::ignore_unused_variable_warning( args );
```
However "args" was not declared in that file or any of the header files that it uses. Therefore I get a `variable not declared` error. I am not sure what to do about this, is `args` really not declared anywhere? Could you check in your computer? If so, should I just comment this line?

Also if I comment this line the compilation goes smoothly until I get:
```sh
/home/acampoverde/Programs/feelpp-0.100.0-beta.7/feel/feelalg/solverlinearpetsc.cpp: In member function ‘void Feel::SolverLinearPetsc<T>::setPetscConstantNullSpace()’:
/home/acampoverde/Programs/feelpp-0.100.0-beta.7/feel/feelalg/solverlinearpetsc.cpp:732:40: error: there are no arguments to ‘KSPSetNullSpace’ that depend on a template parameter, so a declaration of ‘KSPSetNullSpace’ must be available [-fpermissive]
         KSPSetNullSpace( M_ksp, nullsp );
                                        ^
/home/acampoverde/Programs/feelpp-0.100.0-beta.7/feel/feelalg/solverlinearpetsc.cpp:732:40: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/acampoverde/Programs/feelpp-0.100.0-beta.7/feel/feelalg/solverlinearpetsc.cpp: In instantiation of ‘void Feel::SolverLinearPetsc<T>::setPetscConstantNullSpace() [with T = double]’:
/home/acampoverde/Programs/feelpp-0.100.0-beta.7/feel/feelalg/solverlinearpetsc.cpp:991:16:   required from here
/home/acampoverde/Programs/feelpp-0.100.0-beta.7/feel/feelalg/solverlinearpetsc.cpp:732:40: error: ‘KSPSetNullSpace’ was not declared in this scope
make[2]: *** [feel/CMakeFiles/feelpp.dir/feelalg/solverlinearpetsc.cpp.o] Error 1
make[1]: *** [feel/CMakeFiles/feelpp.dir/all] Error 2
make: *** [all] Error 2
```
The message suggests that I should use, while compiling, something like `g++ -fpermisive ...` but I am not sure where to include the "-fpermisive". Any suggestions about this issue?

I configured using:
```sh
cmake .. -DFEELPP_ENABLE_NLOPT=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/acampoverde/Programs/feelpp-0.100.0-beta.7 -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` -DFEELPP_MINIMAL_CONFIGURATION=ON -DFEELPP_ENABLE_QUICKSTART=OFF
```
The author of this code is:

  Author(s): Christophe Prud'homme <christophe.prudhomme@feelpp.org>

So it would be very helpful if he can take a look at this.

Thanks.

**Comment by vhuber** [comment]
Hi @acampove,

Thank you for your feed back.
Have you looked at the [Feel++ Book](http://book.feelpp.org), (in particular the minimum requirement) ?

Few remarks :
- Can you please provide us the **full** log, from the `cmake` configuration to the error that break your compilation ?
- Is there a strong reason to work with the 0.1 version and not the `develop` version available on that repository ?

All the best,

VH.

ps: I formatted your message to help the reader, you should consider doing so, GitHub support [Markdown](https://help.github.com/articles/github-flavored-markdown/)

**Comment by acampove** [comment]
Hi,

If by requirements you mean what is in:

```
g++ >= 5.0 OR clang >= 3.4 for C++14 compatibility
MPI: openmpi (preferred) or mpich
Boost >= 1.55 and <= 1.59
Petsc >= 3.2 and
CMake >= 2.8.7
Gmsh >= 2.8.3 (can be found at http://www.geuz.org/gmsh)
Libxml2
```
No, I have g++ 4.8 but I just Installed clang.x86_64. MPI was installed by petsc and my petsc version is 3.6.2. I have cmake 3.4. Gmsh was downloaded by feel++ after doing cmake. I have Libxml2:

```
Loaded plugins: langpacks
Installed Packages
libxml2.x86_64                                     2.9.1-5.el7_1.2                               @security/$releasever
libxml2-devel.x86_64                               2.9.1-5.el7_1.2                               @sl-security         
libxml2-python.x86_64                              2.9.1-5.el7_1.2                               @security/$releasever
Available Packages
libxml2.i686                                       2.9.1-5.el7_1.2                               sl-security          
libxml2-devel.i686                                 2.9.1-5.el7_1.2                               sl-security          
libxml2-static.i686                                2.9.1-5.el7_1.2                               sl-security          
libxml2-static.x86_64                              2.9.1-5.el7_1.2                               sl-security          
```
Except for libxml2-static.x86_64, which I am installing too just in case.

I am attaching the files in:

```
/home/acampoverde/Programs/feelpp-0.100.0-beta.7/opt/CMakeFiles
```
I hope those are the files you want to see.

[CMakeError.pdf](https://github.com/feelpp/feelpp/files/45258/CMakeError.pdf)
[CMakeOutput.pdf](https://github.com/feelpp/feelpp/files/45259/CMakeOutput.pdf)

If I uncomment the line:

```
    Feel::detail::ignore_unused_variable_warning( args );
```
at line 380 of preconditioner.hpp so that the code stays in the original form and then compile again I get what is in preconditioner_error.pdf  (attached) 
[preconditioner_error.pdf](https://github.com/feelpp/feelpp/files/45262/preconditioner_error.pdf)

If I comment this line the preconditioner part works and I can go all the way until the machine tries to compile a "solver" class, then I get what is in solver_error.pdf (attached).

[solver_error.pdf](https://github.com/feelpp/feelpp/files/45263/solver_error.pdf)

Also I did not know about the developer version. I will try it if you give me the link, I can only find the three  files in:

https://github.com/feelpp/feelpp/releases

Thanks for the Markdown thing.

**Comment by vhuber** [comment]
I'll have a closer look on your data tomorrow, for the moment, to get the latest version, you can use Git:
```sh
git clone https://github.com/feelpp/feelpp.git
```

**Comment by acampove** [comment]
Thanks, I'll try that with clang and clang++ instead of gcc and g++.

**Comment by vhuber** [comment]
@acampove Can you please join us (me) via Gitter (the link is on the [Readme](https://github.com/feelpp/feelpp/blob/develop/README.md) ). It will be easier to discuss about that issue.

**Comment by acampove** [comment]
Hi,

I solved that problem but I am still having troubles. So it seems that I do need gcc 4.9 for the git version, because it uses c++14. I am using Scientific Linux 7 and so it seems that I do need to download and install some "development toolset 3" packages, specifically the ones below.

```
devtoolset-3-gcc-4.9.2-6.el7.x86_64.rpm 
devtoolset-3-libquadmath-devel-4.9.2-6.el7.x86_64.rpm
devtoolset-3-gcc-c++-4.9.2-6.el7.x86_64.rpm       
devtoolset-3-libstdc++-devel-4.9.2-6.el7.x86_64.rpm
devtoolset-3-gcc-gfortran-4.9.2-6.el7.x86_64.rpm 
devtoolset-3-runtime-3.1-12.el7.x86_64.rpm
```

Then in order to tell cmake where to find the libraries I need to do:

```
export LIBRARY_PATH=${LIBRARY_PATH}:/opt/rh/devtoolset-3/root/lib/gcc/x86_64-redhat-linux/4.9.2/
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/rh/devtoolset-3/root/lib/gcc/x86_64-redhat-linux/4.9.2/
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:/opt/rh/devtoolset-3/root/usr/include/c++/4.9.2
export C_INCLUDE_PATH=${C_INCLUDE_PATH}:/opt/rh/devtoolset-3/root/usr/include/c++/4.9.2
```
To turn on gcc 4.9 and turn off the default 4.8 I do:

```
source /opt/rh/devtoolset-3/enable 
```
Then I configure with cmake:
```
cmake .. -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-3/root/usr/bin/g++ -DCMAKE_C_COMPILER=/opt/rh/devtoolset-3/root/usr/bin/gcc
```
Everything seems to be ok there and I finally do make feelpp. Most of the code compiles but then I get compilation errors that are too long to paste here and I have put in the PDF attached.
[modelproperties_error.pdf](https://github.com/feelpp/feelpp/files/48123/modelproperties_error.pdf)

I am not really sure what to do now. Do you have any suggestions? By the way clang is not really necessary, apparently, If you have these devtoolset.

**Comment by prudhomm** [comment]
@acampove unfortunately g++ 4.9 cannot compile completely feel++, you need a c++14 and 4.9 does not support e.g. template variables. that 's why you now need clang >= 3.4 (preferably 3.6 or 3.7, they generate more optimized codes)

**Comment by acampove** [comment]
Hi,

Yes, I finally built it with clang 3.5, I also had to install libc++ and libc++abi. Also the amount of RAM that some of the files take to build is really large.

**Comment by prudhomm** [comment]
Ok thanks for the successful report. regarding memory this is due to our relying a lot on templates and meta programming. I am working on some ways to reduce this but it is very slow going at the moment.
what are you interested in in Feel++ ?

**Comment by acampove** [comment]
Hi,

I want to solve partial differential equations. Maybe introduce the boundary conditions numerically as a number in each point of the boundary of the grid and then get a file with the values of the function at each point in the grid.
